services:
  content_monitoring_system:
    image: ghcr.io/VictorHachard/cms:v1.0.0
    container_name: content_monitoring_system
    environment:
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      INTERVAL: "300"
      RULES: |
        {
          "https://example.com/page": {
            "selectors": ["div.test-selector"],
            "use_selenium": false
          }
        }
    volumes:
      - app_data:/app/data

volumes:
  app_data:
  